# Generated by Django 5.0.7 on 2024-08-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
