# Generated by Django 5.0.7 on 2024-08-16 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_product_description'),
        ('login', '0002_remove_account_id_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.account'),
        ),
    ]
