# Generated by Django 5.0.7 on 2024-08-16 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_product_user'),
        ('login', '0002_remove_account_id_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.account'),
        ),
    ]
